### ISSUE TITLE
Segmentation fault when generating graph.txt

### ISSUE THREAD

**Issue by wangshuaizs** [msr-fiddle/pipedream#1]
Hi,

    
When I ran the cmd `CUDA_VISIBLE_DEVICES=0 python main.py -a vgg16 -b 64 --data_dir <path to ImageNet directory>` to generate graph.txt, everyting went well until it ran to `create_graph(model, train_loader, summary, os.path.join(args.profile_directory, args.arch))`

The following is error log. It seems TensorWrapper is used? Is that a bug?

```
Traceback (most recent call last):
  File "main.py", line 579, in <module>
    main()
  File "main.py", line 289, in main
    os.path.join(args.profile_directory, args.arch))
  File "main.py", line 116, in create_graph
    output = model(input)
  File "/home/user/.conda/envs/pipedream/lib/python3.6/site-packages/torch/nn/modules/module.py", line 509, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/.conda/envs/pipedream/lib/python3.6/site-packages/torchvision/models/vgg.py", line 45, in forward
    x = torch.flatten(x, 1)
TypeError: flatten(): argument 'input' (position 1) must be Tensor, not TensorWrapper
Segmentation fault (core dumped)
```

**Comment by deepakn94** [comment]
Are you running this within a docker container? What PyTorch commit hash are you using?

**Comment by wangshuaizs** [comment]
@deepakn94 This error happened on my physical machine. PyTorch code is from `https://github.com/pytorch/pytorch` with branch `v1.1.0`, and commit hash is `142c973f4179e768164cd578951489e89021b29c`.

I also tried to run it with a docker container. Unfortunately, another error happened when running `main_with_runtime .py`. 

```
Traceback (most recent call last):
  File "main_with_runtime.py", line 578, in <module>
    main()
  File "main_with_runtime.py", line 149, in main
    output_tensors = stage(*tuple(input_tensors))
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 507, in __call__
    result = self.forward(*input, **kwargs)
  File "/pipedream/runtime/image_classification/models/vgg16/gpus=2/stage1.py", line 78, in forward
    out25 = out23.view(out24)
RuntimeError: shape '[64]' is invalid for input of size 1605632
```

BTW, my GPU is K40, so I changed the `TORCH_CUDA_ARCH_LIST` correspondingly. And when the container started, it reported this (though I think the above error is not caused by it ):
```
Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.
ERROR: Detected NVIDIA Tesla K40c GPU, which is not supported by this container
ERROR: Detected NVIDIA Tesla K40c GPU, which is not supported by this container
ERROR: No supported GPU(s) detected to run this container
```

**Comment by wangshuaizs** [comment]
Hi, @deepakn94 . I found the first error `argument 'input' (position 1) must be Tensor, not TensorWrapper` is caused by the newer version of torchvision. After I downgraded it to `v0.2.1`, same as the version in docker, the second error happened again. And I found this is because node 34 is profiled as `View`, which is expected `View(-1)`. Maybe it is also caused by the mismatch version of torchvision? Or the profiler can be more robust?

**Comment by deepakn94** [comment]
Sorry for the late reply! I think the safest thing to do right now is to use the same module versions present in nvidia.nvcr.io/pytorch:1905. I will try reproducing this error on my side tomorrow -- will keep you posted.

**Comment by deepakn94** [comment]
Hi @wangshuaizs, sorry for the delay in getting back to you! I've just pushed 23632d2 to master -- this should fix the problem you're seeing when using `torchvision 0.2.1`. Please let me know if this issue persists!

**Comment by wangshuaizs** [comment]
Hi @deepakn94 , thank you for the fix. It does work. I will close this issue.
