### ISSUE TITLE
RuntimeError: ProcessGroupNCCL does not support send

### ISSUE THREAD

**Issue by ymsdu2004** [msr-fiddle/pipedream#14]
**i run the command as bellow:**
`
worker-0:
python main_with_runtime.py --module models.vgg16.gpus=2 -b 64 --data_dir /home/admin/pipedream/data/sample --rank 0 --local_rank 0 --master_addr localhost --config_path models/vgg16/gpus=2/hybrid_conf.json --distributed_backend nccl

worker-1:
python main_with_runtime.py --module models.vgg16.gpus=2 -b 64 --data_dir /home/admin/pipedream/data/sample --rank 1 --local_rank 1 --master_addr localhost --config_path models/vgg16/gpus=2/hybrid_conf.json --distributed_backend nccl`

**then i got the error:**

`Exception in thread Thread-3:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "../communication.py", line 632, in send_helper_thread
    sub_process_group=sub_process_group)
  File "../communication.py", line 709, in _send
    dist.send(tensor=tensor_shape, dst=dst_rank, tag=tag)
  File "/opt/conda/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 608, in send
    _default_pg.send([tensor], dst, tag).wait()
RuntimeError: ProcessGroupNCCL does not support send

Epoch: 0 Step 0 	Learning rate: 0.100000
Epoch: [0][0/13]	Memory: 6.323 (9.244)`

**Comment by deepakn94** [comment]
Please use `--distributed_backend=gloo` for all non-DP runs (where a model is split over multiple workers).

**Comment by ymsdu2004** [comment]
> Please use `--distributed_backend=gloo` for all non-DP runs (where a model is split over multiple workers).

thanks，it's ok now
