### ISSUE TITLE
tenroflow support

### ISSUE THREAD

**Issue by ymsdu2004** [msr-fiddle/pipedream#15]
@deepakn94 it seems that this project just work for pytorch,  is there any cross-framework（such as tensorflow、mxnet） plan？thanks

**Comment by deepakn94** [comment]
At this current point in time, we are probably just going to focus on improving PyTorch support. We might have ONNX support at some point in the future, but that is more up in the air.

Any particular reason you need to use TensorFlow / MXNet?
