### ISSUE TITLE
Imagenet download url in imagenet.py doesn't work

### ISSUE THREAD

**Issue by kanonjz** [msr-fiddle/pipedream#19]
Imagenet doesn't support direct download, is there any solution?

**Comment by deepakn94** [comment]
It seems like this has been deprecated recently: https://github.com/pytorch/vision/issues/1453.

You will need to figure out a way to download the dataset manually; http://www.image-net.org/challenges/LSVRC/2012/ has more information.

**Comment by kanonjz** [comment]
Thanks, I'll download the dataset manually. But how did you organize the dataset file, could you show me the structure?

**Comment by deepakn94** [comment]
See this: https://pytorch.org/docs/stable/torchvision/datasets.html#torchvision.datasets.ImageFolder. Basically something like `[train|val]/[label]/[image name].jpg`.

**Comment by RylanSchaeffer** [comment]
@deepakn94 , I downloaded a subset of the data and arranged it as you suggested, but I get an error: `{RuntimeError}('Meta file not found or corrupted.', 'You can use download=True to create it.')`

What's this meta file and where can I get it?

**Comment by deepakn94** [comment]
You don't need to run the `download_imagenet.py` script if you have the `train` and `val` directories setup as described above.

**Comment by deepakn94** [comment]
I am going to close this -- please let me know if this did not work for you!

**Comment by kanonjz** [comment]
sorry, I guess it still needs to run the `download_imagenet.py`，because the original val file structure is `[val] / [image name].jpeg `。But it requires `[val]/[label]/[image name].jpeg`, which is what `download_imagenet.py` do. I got an error when run profile:

`
=> creating model 'vgg16'
Traceback (most recent call last):
  File "main.py", line 574, in <module>
    main()
  File "main.py", line 249, in main
    normalize,
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 178, in __init__
    target_transform=target_transform)
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 79, in __init__
    "Supported extensions are: " + ",".join(extensions)))
RuntimeError: Found 0 files in subfolders of: /root/dataset/val
Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif
`

I still don't know how to fix the problem, do you have any suggestion?

**Comment by deepakn94** [comment]
What do you see if you do `/root/dataset/val`?

**Comment by kanonjz** [comment]
Hi, Deepak. I modified the two files `scripts/download_imagenet.py` and `scripts/imagenet.py`. I removed download ImageNet and tested the code successfully. You can see the pull request.

**Comment by deepakn94** [comment]
Great, I merged the PR! Going to close this!
