### ISSUE TITLE
Directory mismatch in example workflow in documentation

### ISSUE THREAD

**Issue by gth828r** [msr-fiddle/pipedream#2]
Hi there, thanks for thoroughly documenting your work and providing examples!  I think I found a documentation issue under https://github.com/msr-fiddle/pipedream#end-to-end-workflow

The second step of optimization, which takes place in `pipedream/optimizer` includes the following:
```
-o ../runtime/models/vgg16/gpus=4
```

This places files under `pipedream/runtime/models`

The next step, running, suggests you navigate over to `pipedream/runtime/image_classification` and then run some commands that include the following:
```
--config_path models/vgg16/gpus=4/hybrid_conf.json
```

This reads files from `pipedream/runtime/image_classification/models`.

Presumably this mismatch is unintentional.

**Comment by deepakn94** [comment]
Hi @gth828r, thanks so much for pointing this out! I've fixed this with c8e703da6df14139232baa4278733cb97638b5e2.
