### ISSUE TITLE
the confused workflow about 1F1B-RR

### ISSUE THREAD

**Issue by gbxu** [msr-fiddle/pipedream#20]
hi, there
 when I read [pipedream](https://cs.stanford.edu/~matei/papers/2019/sosp_pipedream.pdf), I notice that in fig 8, worker 1 will process batch5 after the backward of batch1. Then I read your code, the data parallelism of "1F1B-RR" mechanism is implemented using [DistributedDataParallel](https://github.com/msr-fiddle/pipedream/blob/master/runtime/runtime.py#L258), which, I think, is a sync operator. [--> The docs](https://pytorch.org/docs/stable/nn.html#torch.nn.parallel.DistributedDataParallel).   
So, in my opinion, in fig 8, the forward of batch5 should start after the backward of batch2.  

Do I miss something?

**Comment by deepakn94** [comment]
Sure -- note that the timeline functions exactly the same even with the backward pass of 1 delayed by 2 timesteps (everything is moved back by 2 for worker 1).

**Comment by gbxu** [comment]
thanks @deepakn94 .   
I'll close this issue.
