### ISSUE TITLE
can't find pipedream AMI in AWS console

### ISSUE THREAD

**Issue by kanonjz** [msr-fiddle/pipedream#25]
Hi @deepakn94 , I can't find the AMI in the AWS console by searching the AMI ID or name in `EXPERIMENTS.md`. Is it a public image?

**Comment by deepakn94** [comment]
It is a public AMI. Maybe you're looking in the wrong region? Can you try "North Virginia" (`us-east-1`)?

**Comment by kanonjz** [comment]
yay! I found it in `us-east-1`

**Comment by deepakn94** [comment]
Great! Closing this.
