### ISSUE TITLE
"stage_to_depth_map" not found 

### ISSUE THREAD

**Issue by ADAM-CT** [msr-fiddle/pipedream#38]
Hi! I think I found a problem.
---
With this script [(convert_graph_to_model.py)](https://github.com/msr-fiddle/pipedream/blob/f50827f2e28cbdbd82a4ea686c0498272b1460d6/optimizer/convert_graph_to_model.py) , we can get the configuration file [(vgg16.gpus=16.hybrid_conf.json).](https://github.com/msr-fiddle/pipedream/blob/f50827f2e28cbdbd82a4ea686c0498272b1460d6/runtime/image_classification/models/vgg16/gpus%3D16/hybrid_conf.json#L7) But I didn't find the field "stage_to_depth_map" in the script(convert_graph_to_model.py). This field appears in vgg16.gpus=16.hybrid_conf.json.
`{
    "module_to_stage_map": [0, 1, 1],
    "stage_to_rank_map": {
        "0": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
        "1": [15]
    },
    "stage_to_depth_map": {
        "0": 1,
        "1": 0
    }
}`
 I don't know how this field appears.

**Comment by ADAM-CT** [comment]
After checking the code, we found that without this field, there would be no impact

**Comment by deepakn94** [comment]
`stage_to_depth_map` is an optional field. It's meant to override default logic we have to compute the number of warmup minibatches in each stage: https://github.com/msr-fiddle/pipedream/blob/master/runtime/runtime.py#L166.
