### ISSUE TITLE
Setting -m variable in optimizer_graph_hierarchical.py causes an error

### ISSUE THREAD

**Issue by gth828r** [msr-fiddle/pipedream#4]
https://github.com/msr-fiddle/pipedream/blob/master/optimizer/optimizer_graph_hierarchical.py#L201 includes a variable `num_machines` which has not been defined.  The parameter passed into the `main` function is `all_num_machines` as opposed to `num_machines`.  By default the code is not executed because if `-m` is not set when running the script, then the check is bypassed due to conditional short circuiting.  But if you set the `-m` parameter when calling optimizer_graph_hierarchical.py, then an error is thrown.

**Comment by deepakn94** [comment]
I've removed the `-m` option in b80d16b since most people won't need to use it. Please let me know if you're still running into issues!

**Comment by gth828r** [comment]
The `-m` parameter is no longer recognized, and I don't have problems running without it.  I suppose I didn't fully understand what it was intended for when I was trying it... but if it isn't really used, then I suppose the best thing to do was remove it!  This should be all set.
