### ISSUE TITLE
whats the role of  optimizer/inference_optimizer_graph.py

### ISSUE THREAD

**Issue by ADAM-CT** [msr-fiddle/pipedream#40]
How to use this script？
What does the -t parameter mean? Can you give me an example?
https://github.com/msr-fiddle/pipedream/blob/f50827f2e28cbdbd82a4ea686c0498272b1460d6/optimizer/inference_optimizer_graph.py

**Comment by deepakn94** [comment]
It's meant to create partitionings if you're trying to optimize an inference-related objective. `time_ between_inputs` is the average time between consecutive minibatches (we are trying to optimize a "maximize throughput s.t. inputs can be processed at a given frequency" objective).
