### ISSUE TITLE
Is this the version used in SOSP paper?

### ISSUE THREAD

**Issue by nirandaperera** [msr-fiddle/pipedream#46]
Hi, 

I have been testing this repository to replicate results given in the SOSP paper. 
https://dl.acm.org/doi/abs/10.1145/3341301.3359646

But I was unable to reproduce the results, and I'm seeing some data loading problems for Alexnet. I have started a discussion in PyTorch forum. 
https://discuss.pytorch.org/t/strange-behavior-in-data-loader-with-workers/83769 

So, is this the exact version that was used for the experiments in the SOSP paper?

**Comment by deepakn94** [comment]
Yeah, we either used this or a close variant of this.

For AlexNet, you need to use synthetic data. AlexNet is a small model, and can be bottlenecked by data loading.
