### ISSUE TITLE
Translation demo: Installation instrutions issue. Missing CUDA kernels.

### ISSUE THREAD

**Issue by sergei-mironov** [msr-fiddle/pipedream#48]
Hi. Looks like the installation instructions are incomplete for the Translation task. One need to mention that `gnmt` package has to be installed explicitly with `cd ./runtime/translation; python setup.py install`. Also it is worth mentioning that one may need to change GPU architecture to match their hardware in https://github.com/msr-fiddle/pipedream/blob/master/runtime/translation/setup.py.

Thank you.

**Comment by deepakn94** [comment]
Sorry, this is specified here: https://github.com/msr-fiddle/pipedream/blob/master/EXPERIMENTS.md#updating-docker-container-for-translation. We should be made more visible in the main README perhaps.

**Comment by sergei-mironov** [comment]
My bad, I didn't notice this instruction. Still, in my case, the second part of the issue (missing notice about architecture) was more time-demanding to debug. Please, consider dropping a note it.

**Comment by deepakn94** [comment]
Done, with https://github.com/msr-fiddle/pipedream/commit/b4c50b33023da87acae4427c975ae2d4ba088836!
