### ISSUE TITLE
Does using multiple GPUs on a single machine require the --local_rank option when running?

### ISSUE THREAD

**Issue by gth828r** [msr-fiddle/pipedream#5]
In the top level README, the example workflow has a line that says:
```
[from pipedream/runtime/image_classification; run on 4 GPUs (including a single server with 4 GPUs)]
```

Do those commands actually require setting the `--local_rank` option in order to map the different processes to different GPUs on a single machine setup?  When I run `nvidia-smi`, I am not actually seeing multiple GPUs get used unless I set `--local_rank` to a unique value (between 0 and 4 in my 4 GPU setup).

**Comment by deepakn94** [comment]
Yup, it does. I've updated READMEs with 24acc3a. Btw, using [launch.py](https://github.com/msr-fiddle/pipedream/blob/master/runtime/launch.py) should help automate some of this.
