### ISSUE TITLE
Translation profiler missing __init__.py files for module location?

### ISSUE THREAD

**Issue by gth828r** [msr-fiddle/pipedream#8]
The translation profiler section appears to be have some issues.  When attempting to profile, I ran into the following:
```
# python train.py --dataset-dir /mnt/ptb --target-bleu 21.8 --epochs 20 --math fp16 --print-freq 10 --arch gnmt --batch-size 64 --test-batch-size 128 --model-$onfig "{'num_layers': 4, 'hidden_size': 1024, 'dropout':0.2, 'share_embedding': False}" --optimization-config "{'optimizer': 'FusedAdam', 'lr': 1.75e-3}" --scheduler-config "{'lr_method':'mlperf', 'warmup_iters$:1000, 'remain_steps':1450, 'decay_steps':40}"
Traceback (most recent call last):
  File "train.py", line 20, in <module>
    from seq2seq.models.gnmt import GNMT
ModuleNotFoundError: No module named 'seq2seq.models'
```

I saw that there were local directories for that module, so I added empty `__init__.py` files into `seq2seq` and `seq2seq/models` to get around that.  If the intention is to use these local versions, then you should probably just check in some empty `__init__.py` files into the repo.

**Comment by deepakn94** [comment]
I believe you only need this in `seq2seq` -- I've pushed this in b2c4bee. Let me know if this still doesn't work.

**Comment by gth828r** [comment]
That fixed the issue.  Thanks!
